name: CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: |
          if [ -f package.json ] && grep -q '"lint":' package.json; then
            npm run lint
          else
            echo "No lint script found, skipping lint."
          fi

      - name: Run tests with coverage
        run: |
          if [ -f package.json ] && grep -q '"test":' package.json; then
            npm test -- --coverage
          else
            echo "No test script found."
          fi